services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3410:3410"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
    networks:
      - ben-didnt-tell-me-a-good-name

  postgres:
    image: postgres:16.3
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: printshift
    networks:
      - ben-didnt-tell-me-a-good-name

networks:
  ben-didnt-tell-me-a-good-name:
    name: ben-didnt-tell-me-a-good-name

volumes:
  postgres:
